// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReq) Reset()         { *m = EmptyReq{} }
func (m *EmptyReq) String() string { return proto.CompactTextString(m) }
func (*EmptyReq) ProtoMessage()    {}
func (*EmptyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{0}
}

func (m *EmptyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReq.Unmarshal(m, b)
}
func (m *EmptyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReq.Marshal(b, m, deterministic)
}
func (m *EmptyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReq.Merge(m, src)
}
func (m *EmptyReq) XXX_Size() int {
	return xxx_messageInfo_EmptyReq.Size(m)
}
func (m *EmptyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReq.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReq proto.InternalMessageInfo

type PingReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{1}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

type PongResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PongResp) Reset()         { *m = PongResp{} }
func (m *PongResp) String() string { return proto.CompactTextString(m) }
func (*PongResp) ProtoMessage()    {}
func (*PongResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{2}
}

func (m *PongResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PongResp.Unmarshal(m, b)
}
func (m *PongResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PongResp.Marshal(b, m, deterministic)
}
func (m *PongResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PongResp.Merge(m, src)
}
func (m *PongResp) XXX_Size() int {
	return xxx_messageInfo_PongResp.Size(m)
}
func (m *PongResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PongResp.DiscardUnknown(m)
}

var xxx_messageInfo_PongResp proto.InternalMessageInfo

type ServiceResp struct {
	RequestId            int64    `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceResp) Reset()         { *m = ServiceResp{} }
func (m *ServiceResp) String() string { return proto.CompactTextString(m) }
func (*ServiceResp) ProtoMessage()    {}
func (*ServiceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{3}
}

func (m *ServiceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceResp.Unmarshal(m, b)
}
func (m *ServiceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceResp.Marshal(b, m, deterministic)
}
func (m *ServiceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceResp.Merge(m, src)
}
func (m *ServiceResp) XXX_Size() int {
	return xxx_messageInfo_ServiceResp.Size(m)
}
func (m *ServiceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceResp.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceResp proto.InternalMessageInfo

func (m *ServiceResp) GetRequestId() int64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *ServiceResp) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ServiceResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StartConfig struct {
	MemAlloc             int64    `protobuf:"varint,1,opt,name=mem_alloc,json=memAlloc,proto3" json:"mem_alloc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartConfig) Reset()         { *m = StartConfig{} }
func (m *StartConfig) String() string { return proto.CompactTextString(m) }
func (*StartConfig) ProtoMessage()    {}
func (*StartConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{4}
}

func (m *StartConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartConfig.Unmarshal(m, b)
}
func (m *StartConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartConfig.Marshal(b, m, deterministic)
}
func (m *StartConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartConfig.Merge(m, src)
}
func (m *StartConfig) XXX_Size() int {
	return xxx_messageInfo_StartConfig.Size(m)
}
func (m *StartConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StartConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StartConfig proto.InternalMessageInfo

func (m *StartConfig) GetMemAlloc() int64 {
	if m != nil {
		return m.MemAlloc
	}
	return 0
}

type StatusResp struct {
	ServerState          string   `protobuf:"bytes,1,opt,name=server_state,json=serverState,proto3" json:"server_state,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResp) Reset()         { *m = StatusResp{} }
func (m *StatusResp) String() string { return proto.CompactTextString(m) }
func (*StatusResp) ProtoMessage()    {}
func (*StatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{5}
}

func (m *StatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResp.Unmarshal(m, b)
}
func (m *StatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResp.Marshal(b, m, deterministic)
}
func (m *StatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResp.Merge(m, src)
}
func (m *StatusResp) XXX_Size() int {
	return xxx_messageInfo_StatusResp.Size(m)
}
func (m *StatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResp proto.InternalMessageInfo

func (m *StatusResp) GetServerState() string {
	if m != nil {
		return m.ServerState
	}
	return ""
}

func (m *StatusResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyReq)(nil), "services.EmptyReq")
	proto.RegisterType((*PingReq)(nil), "services.PingReq")
	proto.RegisterType((*PongResp)(nil), "services.PongResp")
	proto.RegisterType((*ServiceResp)(nil), "services.ServiceResp")
	proto.RegisterType((*StartConfig)(nil), "services.StartConfig")
	proto.RegisterType((*StatusResp)(nil), "services.StatusResp")
}

func init() { proto.RegisterFile("cmd.proto", fileDescriptor_7520252fb01eaf30) }

var fileDescriptor_7520252fb01eaf30 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x6d, 0xda, 0xfe, 0xd2, 0xec, 0xe4, 0x77, 0x71, 0x50, 0x09, 0x15, 0xa1, 0xee, 0xa9, 0x78,
	0x88, 0x60, 0x05, 0xcf, 0x22, 0x1e, 0x7a, 0x10, 0x4a, 0x72, 0x37, 0xc4, 0x64, 0x0c, 0x81, 0x6e,
	0x37, 0xcd, 0x6e, 0x05, 0x3f, 0xae, 0xdf, 0x44, 0x76, 0xb3, 0xa1, 0x29, 0xe8, 0x6d, 0xde, 0x9b,
	0xbf, 0xef, 0x0d, 0xb0, 0x42, 0x94, 0x71, 0xd3, 0x4a, 0x2d, 0x31, 0x50, 0xd4, 0x7e, 0xd6, 0x05,
	0x29, 0x0e, 0x10, 0xbc, 0x88, 0x46, 0x7f, 0x25, 0xb4, 0xe7, 0x0c, 0x66, 0x9b, 0x7a, 0x57, 0x99,
	0x10, 0x20, 0xd8, 0x48, 0x13, 0xaa, 0x86, 0xbf, 0x41, 0x98, 0x76, 0xe5, 0x06, 0xe2, 0x35, 0x40,
	0x4b, 0xfb, 0x03, 0x29, 0x9d, 0xd5, 0x65, 0xe4, 0x2d, 0xbc, 0xe5, 0x24, 0x61, 0x8e, 0x59, 0x97,
	0x78, 0x09, 0xbe, 0xd2, 0xb9, 0x3e, 0xa8, 0x68, 0x6c, 0x53, 0x0e, 0x61, 0x04, 0x33, 0x41, 0x4a,
	0xe5, 0x15, 0x45, 0x93, 0x85, 0xb7, 0x64, 0x49, 0x0f, 0xf9, 0x2d, 0x84, 0xa9, 0xce, 0x5b, 0xfd,
	0x2c, 0x77, 0x1f, 0x75, 0x85, 0x57, 0xc0, 0x04, 0x89, 0x2c, 0xdf, 0x6e, 0x65, 0xe1, 0xc6, 0x07,
	0x82, 0xc4, 0x93, 0xc1, 0x7c, 0x0d, 0x90, 0xda, 0x79, 0xf6, 0x94, 0x1b, 0xf8, 0x6f, 0x84, 0x50,
	0x9b, 0x99, 0x25, 0x64, 0xab, 0x59, 0x12, 0x76, 0x9c, 0xa9, 0xa3, 0xe1, 0xda, 0xf1, 0xc9, 0xda,
	0xfb, 0x6f, 0x0f, 0xe0, 0xb5, 0x50, 0x4e, 0x1a, 0xde, 0xc1, 0xd4, 0x88, 0xc7, 0xb3, 0xb8, 0xf7,
	0x26, 0x76, 0x66, 0xcc, 0x71, 0x40, 0xf5, 0xa6, 0x8c, 0xf0, 0x11, 0xfe, 0xd9, 0xb3, 0xf1, 0xe2,
	0x98, 0x1e, 0xe8, 0x98, 0x0f, 0xe9, 0xa3, 0x7d, 0x7c, 0x84, 0x2b, 0x98, 0xa6, 0x5a, 0x36, 0x38,
	0x18, 0xdb, 0xbf, 0xe0, 0xef, 0xa6, 0x07, 0xf0, 0x3b, 0xe1, 0xbf, 0xb6, 0x9d, 0x9f, 0x9c, 0xe0,
	0xec, 0xe1, 0xa3, 0x77, 0xdf, 0xbe, 0x7b, 0xf5, 0x13, 0x00, 0x00, 0xff, 0xff, 0x02, 0x2d, 0x75,
	0x79, 0xfb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// McsServiceClient is the client API for McsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type McsServiceClient interface {
	Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PongResp, error)
	Start(ctx context.Context, in *StartConfig, opts ...grpc.CallOption) (*ServiceResp, error)
	Stop(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*ServiceResp, error)
	Status(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*StatusResp, error)
}

type mcsServiceClient struct {
	cc *grpc.ClientConn
}

func NewMcsServiceClient(cc *grpc.ClientConn) McsServiceClient {
	return &mcsServiceClient{cc}
}

func (c *mcsServiceClient) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PongResp, error) {
	out := new(PongResp)
	err := c.cc.Invoke(ctx, "/services.McsService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcsServiceClient) Start(ctx context.Context, in *StartConfig, opts ...grpc.CallOption) (*ServiceResp, error) {
	out := new(ServiceResp)
	err := c.cc.Invoke(ctx, "/services.McsService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcsServiceClient) Stop(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*ServiceResp, error) {
	out := new(ServiceResp)
	err := c.cc.Invoke(ctx, "/services.McsService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mcsServiceClient) Status(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*StatusResp, error) {
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, "/services.McsService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// McsServiceServer is the server API for McsService service.
type McsServiceServer interface {
	Ping(context.Context, *PingReq) (*PongResp, error)
	Start(context.Context, *StartConfig) (*ServiceResp, error)
	Stop(context.Context, *EmptyReq) (*ServiceResp, error)
	Status(context.Context, *EmptyReq) (*StatusResp, error)
}

// UnimplementedMcsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMcsServiceServer struct {
}

func (*UnimplementedMcsServiceServer) Ping(ctx context.Context, req *PingReq) (*PongResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedMcsServiceServer) Start(ctx context.Context, req *StartConfig) (*ServiceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedMcsServiceServer) Stop(ctx context.Context, req *EmptyReq) (*ServiceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedMcsServiceServer) Status(ctx context.Context, req *EmptyReq) (*StatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

func RegisterMcsServiceServer(s *grpc.Server, srv McsServiceServer) {
	s.RegisterService(&_McsService_serviceDesc, srv)
}

func _McsService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McsServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.McsService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McsServiceServer).Ping(ctx, req.(*PingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _McsService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McsServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.McsService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McsServiceServer).Start(ctx, req.(*StartConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _McsService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McsServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.McsService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McsServiceServer).Stop(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _McsService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(McsServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.McsService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(McsServiceServer).Status(ctx, req.(*EmptyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _McsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.McsService",
	HandlerType: (*McsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _McsService_Ping_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _McsService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _McsService_Stop_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _McsService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd.proto",
}
